### ISSUE TITLE
Setup StyleCop configuration

### ISSUE THREAD

**Issue by achobanov** [achobanov/web-application#16]
## Overview
For consistency's sake we want to make sure we write code in an uniform style. StyleCop is a tool that provides static checks based on configurable rule set. I found a decent guide [here].(https://blog.submain.com/stylecop-detailed-guide/).

## To do
1. Setup StyleCop with default configuration
1. Make any modification to check if the custom rules work appropriately

_I suggest we discuss and setup the initial rules together._

**Comment by DanislavKamenov** [comment]
I've added StyleCop and configured it via global ruleset, applied to every project which has additionally been overridden using a .editorconfig and a stylecop.json to demonstrate how both approaches work.

The idea is to have a global .rulset file that can be easily edited via the VS GUI which is then imported into all projects trough Directory.Build.targets. If necessary we can override the default ruleset by defining exclusions in a .editorconfig file or stylecop.json. I don't think we'll need exclusions in our project but it's always nice to have the option.
