### ISSUE TITLE
Extract Persistence in separate project under Gateways

### ISSUE THREAD

**Issue by achobanov** [achobanov/web-application#5]
## Overview
Persistence is separate boundary which falls under the input/output category, also known as _Gateway_ in DDD terminology. As such it will be nested under `Gateways` directory. And since the `Web` project also falls in the same category, `Persistence` will be isolated in a separate project.

**Comment by DanislavKamenov** [comment]
The issues with the database have been resolved. The branch is ready for code review and merge.
